import argparse
import asyncio
import os
import subprocess
import sys
import time

def install_varity():
    """Install the Varity library locally using pip."""
    print("[1] Installing the 'varity' package locally...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", "."])
    print("[1] Installation complete!\n")

# Run installation straight away before importing
install_varity()

# Now we can safely import varity
from varity import Varity, VarityConfig
from varity.providers import get_provider

# ---------------------------------------------------------
# Native .env parser (Loads keys from a local .env file)
# ---------------------------------------------------------
if os.path.exists(".env"):
    print("[0] Loading API keys dynamically from local .env file...")
    with open(".env", "r", encoding="utf-8") as f:
        for line in f:
            if "=" in line and not line.strip().startswith("#"):
                key, val = line.strip().split("=", 1)
                os.environ[key.strip()] = val.strip()

# Example response generated by some external "upstream" AI system
TARGET_AI_RESPONSE = (
    "The Great Wall of China is exactly 13,170 miles long. "
    "It is clearly visible from space with the naked eye. "
    "It was built mainly during the Ming Dynasty."
)

async def run_cycles(total_cycles: int = 100):
    """Run Varity checking on an AI response in a dynamic loop."""
    print("[2] Setting up Varity...")

    # You can choose your provider by setting VARITY_PROVIDER.
    # Defaults to 'gemini' for the free API tier, but you can set it to 'anthropic' or 'openai' 
    # if you have those subscriptions and prefer the upper-end models.
    provider_name = os.environ.get("VARITY_PROVIDER", "gemini").lower()
    
    # IMPORTANT: Set this environment variable in your terminal before running:
    #   set VARITY_API_KEY=your-api-key
    api_key = os.environ.get("VARITY_API_KEY")
    
    if not api_key:
        print(f"\n[!] CRITICAL: 'VARITY_API_KEY' environment variable is missing.")
        print(f"Please set your API key for the '{provider_name}' provider in your terminal and run this script again:")
        print("  Windows: set VARITY_API_KEY=your_actual_key")
        print("  Linux/Mac: export VARITY_API_KEY=your_actual_key")
        print("Exiting test to avoid provider initialization errors.")
        return

    # Initialize the chosen Provider flexibly
    print(f"Initializing Varity with '{provider_name}' Provider...")
    provider = get_provider(provider_name, api_key=api_key)
    
    # Configure Varity (Setting to "quick" to prevent extreme rate limiting during 100 cycles)
    config = VarityConfig(strategy="quick", confidence_threshold=0.6)
    varity = Varity(provider, config=config)

    print(f"\n[3] Starting the {total_cycles}-cycle validation run...")
    print(f"Target Text: '{TARGET_AI_RESPONSE}'\n")

    hallucinations_caught = 0
    start_time = time.time()

    for cycle in range(1, total_cycles + 1):
        try:
            # We use `acheck` for async execution wrapper 
            result = await varity.acheck(TARGET_AI_RESPONSE)
            
            num_flagged = len(result.flagged_claims)
            
            if num_flagged > 0:
                hallucinations_caught += 1
                flag_str = "DETECTED HALLUCINATION"
            else:
                flag_str = "CLEAN"

            print(
                f"Cycle {cycle:03d} | "
                f"Conf: {result.overall_confidence:.2f} | "
                f"VSS: {result.vss_score:.2f} | "
                f"Flagged: {num_flagged}/{len(result.claims)} | "
                f"Status: {flag_str}"
            )
            
            # Brief sleep to respect API concurrent limitations during the 100 loops
            await asyncio.sleep(1)

        except Exception as exc:
            # Varity's _retry logic handles 429/500 errors gracefully, but if 
            # all retries are completely exhausted, it bubbles here.
            print(f"Cycle {cycle:03d} | ERROR — Request failed or timed out: {exc}")
            # Longer backoff if the API is overwhelmed
            await asyncio.sleep(5)

    # Context manager gracefully closes the client, but manually invoking clean up:
    await provider.close()
    
    duration = time.time() - start_time

    # Final Summary Statistics
    print("\n" + "="*50)
    print("                 FINAL REPORT")
    print("="*50)
    print(f"Total Cycles         : {total_cycles}")
    print(f"Successful Flags     : {hallucinations_caught}")
    print(f"Missed/Failed        : {total_cycles - hallucinations_caught}")
    print(f"Total Execution Time : {duration:.1f} seconds")
    print(f"Avg Time per Check   : {(duration / total_cycles):.1f} seconds")
    print("="*50)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test Varity's hallucination detection over multiple cycles.")
    parser.add_argument(
        "--cycles", 
        type=int, 
        default=int(os.environ.get("VARITY_CYCLES", "100")),
        help="Number of cycles to run the test for (default: 100 or VARITY_CYCLES env var)"
    )
    args = parser.parse_args()

    try:
        # Run the internal async loop with the dynamic cycle count
        asyncio.run(run_cycles(args.cycles))
    except KeyboardInterrupt:
        print("\n[!] Test manually interrupted by user.")
